### ISSUE TITLE
Cannot parse event names containing ':' from json

### ISSUE THREAD

**Issue by carpodaster** [Absolventa/ereignishorizont#44]
ActionDispatch::ParamsParser::ParseError (795: unexpected token at '{"api_token":"88bad8d3ad2d83d4197b5757e8fa8fd6","incoming_event":{"title":""crlwatch:","content":"CRL"}}')

**Comment by rstammer** [comment]
Ereignishorizont has been marked as deprecated, therefore I'll close this one, despite its usefulness of the original project…
