### ISSUE TITLE
Make other input field disappear in expected_events/new

### ISSUE THREAD

**Issue by FrauBienenstich** [Absolventa/ereignishorizont#9]
So far you can choose an option from the drop down AND type in your own at the same time. The one you type in will be preferred then, as far as I can see it. Maybe we can make the upper input field disappear once you've selected from the drop down menu, and the other way round. 
I guess that would involve some javascript? And can probably wait a little longer.

**Comment by rstammer** [comment]
Ereignishorizont has been marked as deprecated, therefore I'll close this one, despite its usefulness of the original project…
